#!/bin/sh

export SXHKD_SHELL=/bin/bash
sxhkd &

bspc config border_width         4
bspc config window_gap           15

bspc config automatic_scheme     "longest_side"
bspc config removal_adjustment   none
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config click_to_focus any
bspc config focus_follows_pointer false
bspc config initial_polarity      first_child

bspc config bottom_padding 10
bspc config top_padding 40

## Border colors
bspc config normal_border_color "#000000"
bspc config focused_border_color "#1793d0"
bspc config urgent_border_color "#b58900"
bspc config presel_feedback_color "#1d1d1d"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# wallpaper
$HOME/.config/bspwm/wallpaper.sh

# miscellaneous bits
compton -bc -t -8 -l -9 -r 6 -o 1.0 &
#devilspie2 &
#dropbox &

nm-applet &
bash -c "xset r rate 200 30"
/usr/bin/polybar main &
plank &
redshift -t 6500:3500 -b 1.0:0.7 &
xautolock -time 15 -locker "i3lock -c 000000 -u && sleep 1" &
